routes/web.php
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Castes
    Route::delete('castes/destroy', 'CasteController@massDestroy')->name('castes.massDestroy');
    Route::resource('castes', 'CasteController');

    // Coursetypes
    Route::delete('coursetypes/destroy', 'CoursetypeController@massDestroy')->name('coursetypes.massDestroy');
    Route::resource('coursetypes', 'CoursetypeController');

    // Courses
    Route::delete('courses/destroy', 'CoursesController@massDestroy')->name('courses.massDestroy');
    Route::resource('courses', 'CoursesController');

    // Categories
    Route::delete('categories/destroy', 'CategoryController@massDestroy')->name('categories.massDestroy');
    Route::resource('categories', 'CategoryController');

    // Scholarship Providers

   
    Route::delete('scholarship-providers/destroy', 'ScholarshipProvidersController@massDestroy')->name('scholarship-providers.massDestroy');
    Route::resource('scholarship-providers', 'ScholarshipProvidersController');

    // Scholarships

    Route::delete('scholarships/destroy', 'ScholarshipsController@massDestroy')->name('scholarships.massDestroy');
    Route::post('scholarships/media', 'ScholarshipsController@storeMedia')->name('scholarships.storeMedia');
    Route::post('scholarships/ckmedia', 'ScholarshipsController@storeCKEditorImages')->name('scholarships.storeCKEditorImages');
    Route::resource('scholarships', 'ScholarshipsController');

   

    // Profiles
    Route::delete('profiles/destroy', 'ProfilesController@massDestroy')->name('profiles.massDestroy');
    Route::resource('profiles', 'ProfilesController');



    // Scholarship Achievers
    Route::delete('scholarship-achievers/destroy', 'ScholarshipAchieversController@massDestroy')->name('scholarship-achievers.massDestroy');
    Route::post('scholarship-achievers/media', 'ScholarshipAchieversController@storeMedia')->name('scholarship-achievers.storeMedia');
    Route::post('scholarship-achievers/ckmedia', 'ScholarshipAchieversController@storeCKEditorImages')->name('scholarship-achievers.storeCKEditorImages');
    Route::resource('scholarship-achievers', 'ScholarshipAchieversController');

     // Ticketcategories
    Route::delete('ticketcategories/destroy', 'TicketcategoriesController@massDestroy')->name('ticketcategories.massDestroy');
    Route::resource('ticketcategories', 'TicketcategoriesController');

    // Tickets
    Route::delete('tickets/destroy', 'TicketsController@massDestroy')->name('tickets.massDestroy');
    Route::resource('tickets', 'TicketsController');

    // Faq Categories
    Route::delete('faq-categories/destroy', 'FaqCategoryController@massDestroy')->name('faq-categories.massDestroy');
    Route::resource('faq-categories', 'FaqCategoryController');

    // Faq Questions
    Route::delete('faq-questions/destroy', 'FaqQuestionController@massDestroy')->name('faq-questions.massDestroy');
    Route::resource('faq-questions', 'FaqQuestionController');
    
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});



Route::get('/students','Student\HomeController@index')->name('students.home');

Route::get('/preview','Student\ProfileController@preview')->name('preview');
//Student Profile Controller
Route::group(['prefix' => 'student','namespace' => 'Student'], function(){

Route::get('/createprofile','ProfileController@create')->name('createprofile');

Route::POST('/details','ProfileController@updatedetails')->name('details');
Route::POST('/servicepreview','ProfileController@servicedetails')->name('servicepreview');

Route::POST('/createprofile','ProfileController@store')->name('storeprofile');
Route::get('/editprofile/{id}','ProfileController@edit')->name('editprofile');
Route::POST('updateprofile/{id}','ProfileController@update')->name('updateprofile');



Route::get('course/get_coursetype','ProfileController@getcourse')->name('getcourse');

Route::get('documents','ProfileController@documents')->name('documents');
Route::POST('aadharupload','ProfileController@aadharupload')->name('aadharupload');

Route::POST('panupload','ProfileController@panupload')->name('panupload');
Route::POST('casteupload','ProfileController@casteupload')->name('casteupload');
Route::POST('phupload','ProfileController@phupload')->name('phupload');
Route::POST('deathupload','ProfileController@deathupload')->name('deathupload');
Route::POST('photoupload','ProfileController@photoupload')->name('photoupload');
Route::POST('addproofupload','ProfileController@addproofupload')->name('addproofupload');
Route::POST('domupload','ProfileController@domupload')->name('domupload');
Route::POST('icupload','ProfileController@icupload')->name('icupload');
Route::POST('passbookupload','ProfileController@passbookupload')->name('passbookupload');
Route::POST('clgidupload','ProfileController@clgidupload')->name('clgidupload');
Route::POST('bonafideupload','ProfileController@bonafideupload')->name('bonafideupload');
Route::POST('admissionupload','ProfileController@admissionupload')->name('admissionupload');
Route::POST('cfupload','ProfileController@cfupload')->name('cfupload');
Route::POST('hfupload','ProfileController@hfupload')->name('hfupload');
Route::POST('class10upload','ProfileController@class10upload')->name('class10upload');
Route::POST('class12upload','ProfileController@class12upload')->name('class12upload');
Route::POST('diplomaupload','ProfileController@diplomaupload')->name('diplomaupload');
Route::POST('gradupload','ProfileController@gradupload')->name('gradupload');
Route::POST('prevupload','ProfileController@prevupload')->name('prevupload');



//sfc

Route::get('preview','ProfileController@sfc')->name('sfc');



 //Student Search & Apply Scholarship

Route::get('/myscholarship','HomeController@myscholarship')->name('myscholarship');

Route::get('/details/{id}','HomeController@showdetails')->name('showdetails');

//Support Controller
Route::get('/support','TicketsController@index')->name('support');

Route::get('/createquery','TicketsController@create')->name('createquery');
Route::POST('storequery','TicketsController@store')->name('storequery');

Route::get('viewresponse/{id}','TicketsController@show')->name('response');
});

 Route::get('showapplications/{id}','SetupscholarshipController@showapplications')->name('showapplications');

Route::get('filteredview/{id}','ScholarshipProvider\SetupscholarshipController@filteredview')->name('filteredview');
Route::get('/scholarshipproviders','ScholarshipProvider\HomeController@index')->name('providers.home');
Route::get('/sfcngostudentlist','SFCNGO\HomeController@sfc_student_list')->name('sfc_student_list');

Route::get('/sfcngo','SFCNGO\HomeController@index')->name('sfc.home');

Route::GET('/sfcngo/applications','SFCNGO\HomeController@sfcapplications')->name('sfcapplications');
Route::POST('sfcsearchstatus','SFCNGO\HomeController@searchstatus')->name('sfcsearchstatus');
Route::GET('profileshow/{id}','SFCNGO\HomeController@profileshow')->name('profileshow');

Route::group(['prefix'=>'provider','namespace'=>'ScholarshipProvider'],function(){

     Route::delete('setupscholarships/destroy', 'SetupscholarshipController@massDestroy')->name('massDestroy');
    Route::post('setupscholarships/media', 'SetupscholarshipController@storeMedia')->name('setupscholarships.storeMedia');
    Route::post('setupscholarships/ckmedia', 'SetupscholarshipController@storeCKEditorImages')->name('setupscholarships.storeCKEditorImages');
    Route::resource('setupscholarships', 'SetupscholarshipController');

    Route::get('promotion','SetupscholarshipController@promotion')->name('promotion');
    Route::get('setup','SetupscholarshipController@index')->name('setup');
    Route::get('listscheme','SetupscholarshipController@listscheme')->name('listscheme');
     Route::get('createschol','SetupscholarshipController@create')->name('createscholarship');
       Route::POST('createschol','SetupscholarshipController@store')->name('storescholarship');

    Route::get('show/{id}','SetupscholarshipController@show')->name('showscholarship');
    Route::get('edit/{id}','SetupscholarshipController@edit')->name('editscholarship');
    Route::POST('edit/{id}','SetupscholarshipController@update')->name('updatescholarship');
    Route::DELETE('delete/{id}','SetupscholarshipController@destroy')->name('deletescholarship');

    Route::get('showp/{id}','SetupscholarshipController@showprofile')->name('showprofile');
    Route::get('showapplications/{id}','SetupscholarshipController@showapplications')->name('showapplications');



});
Route::POST('applications/{id}','Student\HomeController@apply')->name('apply');
Route::get('/shortlisted/{id}','ScholarshipProvider\HomeController@Shortlised')->name('Shortlised');
Route::get('/rejected/{id}','ScholarshipProvider\HomeController@Rejected')->name('Rejected');
Route::get('/awarded/{id}','ScholarshipProvider\HomeController@Awarded')->name('Awarded');
Route::get('scholarships/applications','Admin\ScholarshipsController@applicant')->name('viewapplicant');
Route::get('/sco/{id}','Admin\ScholarshipsController@sco')->name('sco');

app/FaqQuestion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class FaqQuestion extends Model
{
    //
    use SoftDeletes;

    public $table = 'faq_questions';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'category_id',
        'question',
        'answer',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function category()
    {
        return $this->belongsTo(FaqCategory::class, 'category_id');
    }
}

app/Http/Controllers/Admin/FaqQuestionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\FaqCategory;
use App\FaqQuestion;
use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyFaqQuestionRequest;
use App\Http\Requests\StoreFaqQuestionRequest;
use App\Http\Requests\UpdateFaqQuestionRequest;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class FaqQuestionController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('faq_question_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $faqQuestions = FaqQuestion::all();

        return view('admin.faqQuestions.index', compact('faqQuestions'));
    }

    public function create()
    {
        abort_if(Gate::denies('faq_question_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $categories = FaqCategory::all()->pluck('category', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.faqQuestions.create', compact('categories'));
    }

    public function store(StoreFaqQuestionRequest $request)
    {
        $faqQuestion = FaqQuestion::create($request->all());

        return redirect()->route('admin.faq-questions.index');
    }

    public function edit(FaqQuestion $faqQuestion)
    {
        abort_if(Gate::denies('faq_question_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $categories = FaqCategory::all()->pluck('category', 'id')->prepend(trans('global.pleaseSelect'), '');

        $faqQuestion->load('category');

        return view('admin.faqQuestions.edit', compact('categories', 'faqQuestion'));
    }

    public function update(UpdateFaqQuestionRequest $request, FaqQuestion $faqQuestion)
    {
        $faqQuestion->update($request->all());

        return redirect()->route('admin.faq-questions.index');
    }

    public function show(FaqQuestion $faqQuestion)
    {
        abort_if(Gate::denies('faq_question_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $faqQuestion->load('category');

        return view('admin.faqQuestions.show', compact('faqQuestion'));
    }

    public function destroy(FaqQuestion $faqQuestion)
    {
        abort_if(Gate::denies('faq_question_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $faqQuestion->delete();

        return back();
    }

    public function massDestroy(MassDestroyFaqQuestionRequest $request)
    {
        FaqQuestion::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/faqQuestions/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.faqQuestion.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.faq-questions.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="category_id">{{ trans('cruds.faqQuestion.fields.category') }}</label>
                <select class="form-control select2 {{ $errors->has('category') ? 'is-invalid' : '' }}" name="category_id" id="category_id" required>
                    @foreach($categories as $id => $category)
                        <option value="{{ $id }}" {{ old('category_id') == $id ? 'selected' : '' }}>{{ $category }}</option>
                    @endforeach
                </select>
                @if($errors->has('category'))
                    <div class="invalid-feedback">
                        {{ $errors->first('category') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.faqQuestion.fields.category_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="question">{{ trans('cruds.faqQuestion.fields.question') }}</label>
                <textarea class="form-control {{ $errors->has('question') ? 'is-invalid' : '' }}" name="question" id="question">{!! old('question') !!}</textarea>
                @if($errors->has('question'))
                    <div class="invalid-feedback">
                        {{ $errors->first('question') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.faqQuestion.fields.question_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="answer">{{ trans('cruds.faqQuestion.fields.answer') }}</label>
                <textarea class="form-control ckeditor {{ $errors->has('answer') ? 'is-invalid' : '' }}" name="answer" id="answer">{!! old('answer') !!}</textarea>
                @if($errors->has('answer'))
                    <div class="invalid-feedback">
                        {{ $errors->first('answer') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.faqQuestion.fields.answer_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    $(document).ready(function () {
  function SimpleUploadAdapter(editor) {
    editor.plugins.get('FileRepository').createUploadAdapter = function(loader) {
      return {
        upload: function() {
          return loader.file
            .then(function (file) {
              return new Promise(function(resolve, reject) {
                // Init request
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '/admin/faq-questions/ckmedia', true);
                xhr.setRequestHeader('x-csrf-token', window._token);
                xhr.setRequestHeader('Accept', 'application/json');
                xhr.responseType = 'json';

                // Init listeners
                var genericErrorText = `Couldn't upload file: ${ file.name }.`;
                xhr.addEventListener('error', function() { reject(genericErrorText) });
                xhr.addEventListener('abort', function() { reject() });
                xhr.addEventListener('load', function() {
                  var response = xhr.response;

                  if (!response || xhr.status !== 201) {
                    return reject(response && response.message ? `${genericErrorText}\n${xhr.status} ${response.message}` : `${genericErrorText}\n ${xhr.status} ${xhr.statusText}`);
                  }

                  $('form').append('<input type="hidden" name="ck-media[]" value="' + response.id + '">');

                  resolve({ default: response.url });
                });

                if (xhr.upload) {
                  xhr.upload.addEventListener('progress', function(e) {
                    if (e.lengthComputable) {
                      loader.uploadTotal = e.total;
                      loader.uploaded = e.loaded;
                    }
                  });
                }

                // Send request
                var data = new FormData();
                data.append('upload', file);
                data.append('crud_id', {{ $faqQuestion->id ?? 0 }});
                xhr.send(data);
              });
            })
        }
      };
    }
  }

  var allEditors = document.querySelectorAll('.ckeditor');
  for (var i = 0; i < allEditors.length; ++i) {
    ClassicEditor.create(
      allEditors[i], {
        extraPlugins: [SimpleUploadAdapter]
      }
    );
  }
});
</script>

@endsection

resources/views/admin/faqQuestions/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.faqQuestion.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.faq-questions.update", [$faqQuestion->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="category_id">{{ trans('cruds.faqQuestion.fields.category') }}</label>
                <select class="form-control select2 {{ $errors->has('category') ? 'is-invalid' : '' }}" name="category_id" id="category_id" required>
                    @foreach($categories as $id => $category)
                        <option value="{{ $id }}" {{ ($faqQuestion->category ? $faqQuestion->category->id : old('category_id')) == $id ? 'selected' : '' }}>{{ $category }}</option>
                    @endforeach
                </select>
                @if($errors->has('category'))
                    <div class="invalid-feedback">
                        {{ $errors->first('category') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.faqQuestion.fields.category_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="question">{{ trans('cruds.faqQuestion.fields.question') }}</label>
                <textarea class="form-control  {{ $errors->has('question') ? 'is-invalid' : '' }}" name="question" id="question">{!! old('question', $faqQuestion->question) !!}</textarea>
                @if($errors->has('question'))
                    <div class="invalid-feedback">
                        {{ $errors->first('question') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.faqQuestion.fields.question_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="answer">{{ trans('cruds.faqQuestion.fields.answer') }}</label>
                <textarea class="form-control ckeditor {{ $errors->has('answer') ? 'is-invalid' : '' }}" name="answer" id="answer">{!! old('answer', $faqQuestion->answer) !!}</textarea>
                @if($errors->has('answer'))
                    <div class="invalid-feedback">
                        {{ $errors->first('answer') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.faqQuestion.fields.answer_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    $(document).ready(function () {
  function SimpleUploadAdapter(editor) {
    editor.plugins.get('FileRepository').createUploadAdapter = function(loader) {
      return {
        upload: function() {
          return loader.file
            .then(function (file) {
              return new Promise(function(resolve, reject) {
                // Init request
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '/admin/faq-questions/ckmedia', true);
                xhr.setRequestHeader('x-csrf-token', window._token);
                xhr.setRequestHeader('Accept', 'application/json');
                xhr.responseType = 'json';

                // Init listeners
                var genericErrorText = `Couldn't upload file: ${ file.name }.`;
                xhr.addEventListener('error', function() { reject(genericErrorText) });
                xhr.addEventListener('abort', function() { reject() });
                xhr.addEventListener('load', function() {
                  var response = xhr.response;

                  if (!response || xhr.status !== 201) {
                    return reject(response && response.message ? `${genericErrorText}\n${xhr.status} ${response.message}` : `${genericErrorText}\n ${xhr.status} ${xhr.statusText}`);
                  }

                  $('form').append('<input type="hidden" name="ck-media[]" value="' + response.id + '">');

                  resolve({ default: response.url });
                });

                if (xhr.upload) {
                  xhr.upload.addEventListener('progress', function(e) {
                    if (e.lengthComputable) {
                      loader.uploadTotal = e.total;
                      loader.uploaded = e.loaded;
                    }
                  });
                }

                // Send request
                var data = new FormData();
                data.append('upload', file);
                data.append('crud_id', {{ $faqQuestion->id ?? 0 }});
                xhr.send(data);
              });
            })
        }
      };
    }
  }

  var allEditors = document.querySelectorAll('.ckeditor');
  for (var i = 0; i < allEditors.length; ++i) {
    ClassicEditor.create(
      allEditors[i], {
        extraPlugins: [SimpleUploadAdapter]
      }
    );
  }
});
</script>

@endsection

resources/views/admin/faqQuestions/index.blade.php
@extends('layouts.admin')
@section('content')
@can('faq_question_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.faq-questions.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.faqQuestion.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.faqQuestion.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-FaqQuestion">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.faqQuestion.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.faqQuestion.fields.category') }}
                        </th>
                        <th>
                            Action&nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($faqQuestions as $key => $faqQuestion)
                        <tr data-entry-id="{{ $faqQuestion->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $faqQuestion->id ?? '' }}
                            </td>
                            <td>
                                {{ $faqQuestion->category->category ?? '' }}
                            </td>
                            <td>
                                @can('faq_question_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.faq-questions.show', $faqQuestion->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('faq_question_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.faq-questions.edit', $faqQuestion->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('faq_question_delete')
                                    <form action="{{ route('admin.faq-questions.destroy', $faqQuestion->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('faq_question_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.faq-questions.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-FaqQuestion:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/faqQuestions/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.faqQuestion.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.faq-questions.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.faqQuestion.fields.id') }}
                        </th>
                        <td>
                            {{ $faqQuestion->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.faqQuestion.fields.category') }}
                        </th>
                        <td>
                            {{ $faqQuestion->category->category ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.faqQuestion.fields.question') }}
                        </th>
                        <td>
                            {!! $faqQuestion->question !!}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.faqQuestion.fields.answer') }}
                        </th>
                        <td>
                            {!! $faqQuestion->answer !!}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.faq-questions.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection