routes/web.php
Route::POST('student_course_update/{id}','Admin\StudentCourseController@update')->name('student_course_update');



Route::POST('paid/{id}','Admin\ProfilesController@paid')->name('paid');
Route::POST('sfcstu/{id}','Admin\ProfilesController@sfcstu')->name('sfcstu');
Route::get('scholarship-providers/sfc-ngo-create', 'Admin\ScholarshipProvidersController@sfccreate')->name('sfccreate');
Route::POST('scholarship-providers/sfc-ngo', 'Admin\ScholarshipProvidersController@sfcstore')->name('sfcstore');
Route::POST('/updatestudentdetails/{id}','Admin\ProfilesController@updatedetails')->name('updatestudentdetails');
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Castes
    Route::delete('castes/destroy', 'CasteController@massDestroy')->name('castes.massDestroy');
    Route::resource('castes', 'CasteController');

    // Coursetypes
    Route::delete('coursetypes/destroy', 'CoursetypeController@massDestroy')->name('coursetypes.massDestroy');
    Route::resource('coursetypes', 'CoursetypeController');

    // Courses
    Route::delete('courses/destroy', 'CoursesController@massDestroy')->name('courses.massDestroy');
    Route::resource('courses', 'CoursesController');

    // Categories
    Route::delete('categories/destroy', 'CategoryController@massDestroy')->name('categories.massDestroy');
    Route::resource('categories', 'CategoryController');

    // Scholarship Providers

   
    Route::delete('scholarship-providers/destroy', 'ScholarshipProvidersController@massDestroy')->name('scholarship-providers.massDestroy');
    Route::resource('scholarship-providers', 'ScholarshipProvidersController');

    // Scholarships

    Route::delete('scholarships/destroy', 'ScholarshipsController@massDestroy')->name('scholarships.massDestroy');
    Route::post('scholarships/media', 'ScholarshipsController@storeMedia')->name('scholarships.storeMedia');
    Route::post('scholarships/ckmedia', 'ScholarshipsController@storeCKEditorImages')->name('scholarships.storeCKEditorImages');
    Route::resource('scholarships', 'ScholarshipsController');

   

    // Profiles
    Route::delete('profiles/destroy', 'ProfilesController@massDestroy')->name('profiles.massDestroy');
    Route::resource('profiles', 'ProfilesController');



    // Scholarship Achievers
    Route::delete('scholarship-achievers/destroy', 'ScholarshipAchieversController@massDestroy')->name('scholarship-achievers.massDestroy');
    Route::post('scholarship-achievers/media', 'ScholarshipAchieversController@storeMedia')->name('scholarship-achievers.storeMedia');
    Route::post('scholarship-achievers/ckmedia', 'ScholarshipAchieversController@storeCKEditorImages')->name('scholarship-achievers.storeCKEditorImages');
    Route::resource('scholarship-achievers', 'ScholarshipAchieversController');

     // Ticketcategories
    Route::delete('ticketcategories/destroy', 'TicketcategoriesController@massDestroy')->name('ticketcategories.massDestroy');
    Route::resource('ticketcategories', 'TicketcategoriesController');

    // Tickets
    Route::delete('tickets/destroy', 'TicketsController@massDestroy')->name('tickets.massDestroy');
    Route::resource('tickets', 'TicketsController');

    // Faq Categories
    Route::delete('faq-categories/destroy', 'FaqCategoryController@massDestroy')->name('faq-categories.massDestroy');
    Route::resource('faq-categories', 'FaqCategoryController');

    // Faq Questions
    Route::delete('faq-questions/destroy', 'FaqQuestionController@massDestroy')->name('faq-questions.massDestroy');
    Route::resource('faq-questions', 'FaqQuestionController');
    
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});



Route::get('/students','Student\HomeController@index')->name('students.home');

Route::get('/preview','Student\ProfileController@preview')->name('preview');
//Student Profile Controller
Route::group(['prefix' => 'student','namespace' => 'Student'], function(){

Route::get('/createprofile','ProfileController@create')->name('createprofile');

Route::POST('/details','ProfileController@updatedetails')->name('details');
Route::POST('/servicepreview','ProfileController@servicedetails')->name('servicepreview');

Route::POST('/createprofile','ProfileController@store')->name('storeprofile');
Route::get('/editprofile/{id}','ProfileController@edit')->name('editprofile');
Route::POST('updateprofile/{id}','ProfileController@update')->name('updateprofile');



Route::get('course/get_coursetype','ProfileController@getcourse')->name('getcourse');

Route::get('documents','ProfileController@documents')->name('documents');
Route::POST('aadharupload','ProfileController@aadharupload')->name('aadharupload');

Route::POST('panupload','ProfileController@panupload')->name('panupload');
Route::POST('casteupload','ProfileController@casteupload')->name('casteupload');
Route::POST('phupload','ProfileController@phupload')->name('phupload');
Route::POST('deathupload','ProfileController@deathupload')->name('deathupload');
Route::POST('photoupload','ProfileController@photoupload')->name('photoupload');
Route::POST('addproofupload','ProfileController@addproofupload')->name('addproofupload');
Route::POST('domupload','ProfileController@domupload')->name('domupload');
Route::POST('icupload','ProfileController@icupload')->name('icupload');
Route::POST('passbookupload','ProfileController@passbookupload')->name('passbookupload');
Route::POST('clgidupload','ProfileController@clgidupload')->name('clgidupload');
Route::POST('bonafideupload','ProfileController@bonafideupload')->name('bonafideupload');
Route::POST('admissionupload','ProfileController@admissionupload')->name('admissionupload');
Route::POST('cfupload','ProfileController@cfupload')->name('cfupload');
Route::POST('hfupload','ProfileController@hfupload')->name('hfupload');
Route::POST('class10upload','ProfileController@class10upload')->name('class10upload');
Route::POST('class12upload','ProfileController@class12upload')->name('class12upload');
Route::POST('diplomaupload','ProfileController@diplomaupload')->name('diplomaupload');
Route::POST('gradupload','ProfileController@gradupload')->name('gradupload');
Route::POST('prevupload','ProfileController@prevupload')->name('prevupload');



//sfc

Route::get('preview','ProfileController@sfc')->name('sfc');



 //Student Search & Apply Scholarship

Route::get('/myscholarship','HomeController@myscholarship')->name('myscholarship');

Route::get('/details/{id}','HomeController@showdetails')->name('showdetails');

//Support Controller
Route::get('/support','TicketsController@index')->name('support');

Route::get('/createquery','TicketsController@create')->name('createquery');
Route::POST('storequery','TicketsController@store')->name('storequery');

Route::get('viewresponse/{id}','TicketsController@show')->name('response');
});

 Route::get('showapplications/{id}','SetupscholarshipController@showapplications')->name('showapplications');

Route::get('filteredview/{id}','ScholarshipProvider\SetupscholarshipController@filteredview')->name('filteredview');
Route::get('/scholarshipproviders','ScholarshipProvider\HomeController@index')->name('providers.home');
Route::get('/sfcngostudentlist','SFCNGO\HomeController@sfc_student_list')->name('sfc_student_list');

Route::get('/sfcngo','SFCNGO\HomeController@index')->name('sfc.home');

Route::GET('/sfcngo/applications','SFCNGO\HomeController@sfcapplications')->name('sfcapplications');
Route::POST('sfcsearchstatus','SFCNGO\HomeController@searchstatus')->name('sfcsearchstatus');
Route::GET('profileshow/{id}','SFCNGO\HomeController@profileshow')->name('profileshow');

Route::group(['prefix'=>'provider','namespace'=>'ScholarshipProvider'],function(){

     Route::delete('setupscholarships/destroy', 'SetupscholarshipController@massDestroy')->name('massDestroy');
    Route::post('setupscholarships/media', 'SetupscholarshipController@storeMedia')->name('setupscholarships.storeMedia');
    Route::post('setupscholarships/ckmedia', 'SetupscholarshipController@storeCKEditorImages')->name('setupscholarships.storeCKEditorImages');
    Route::resource('setupscholarships', 'SetupscholarshipController');

    Route::get('promotion','SetupscholarshipController@promotion')->name('promotion');
    Route::get('setup','SetupscholarshipController@index')->name('setup');
    Route::get('listscheme','SetupscholarshipController@listscheme')->name('listscheme');
     Route::get('createschol','SetupscholarshipController@create')->name('createscholarship');
       Route::POST('createschol','SetupscholarshipController@store')->name('storescholarship');

    Route::get('show/{id}','SetupscholarshipController@show')->name('showscholarship');
    Route::get('edit/{id}','SetupscholarshipController@edit')->name('editscholarship');
    Route::POST('edit/{id}','SetupscholarshipController@update')->name('updatescholarship');
    Route::DELETE('delete/{id}','SetupscholarshipController@destroy')->name('deletescholarship');

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class Ticket extends Model
{
    //
     use SoftDeletes;

    public $table = 'tickets';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    const STATUS_SELECT = [
        'Open'   => 'Open',
        'Closed' => 'Closed',
    ];

    protected $fillable = [
        'userid',
        'categoryid_id',
        'query',
        'status',
        'response',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function categoryid()
    {
        return $this->belongsTo(Ticketcategory::class, 'categoryid_id');
    }
}

app/Http/Controllers/Admin/TicketsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyTicketRequest;
use App\Http\Requests\StoreTicketRequest;
use App\Http\Requests\UpdateTicketRequest;
use App\Ticket;
use App\Ticketcategory;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class TicketsController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('ticket_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tickets = Ticket::all();

        return view('admin.tickets.index', compact('tickets'));
    }

    public function create()
    {
        abort_if(Gate::denies('ticket_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $categoryids = Ticketcategory::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.tickets.create', compact('categoryids'));
    }

    public function store(StoreTicketRequest $request)
    {
        $ticket = Ticket::create($request->all());

        return redirect()->route('admin.tickets.index');
    }

    public function edit(Ticket $ticket)
    {
        abort_if(Gate::denies('ticket_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $categoryids = Ticketcategory::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $ticket->load('categoryid');

        return view('admin.tickets.edit', compact('categoryids', 'ticket'));
    }

    public function update(UpdateTicketRequest $request, Ticket $ticket)
    {
        $ticket->update($request->all());

        return redirect()->route('admin.tickets.index');
    }

    public function show(Ticket $ticket)
    {
        abort_if(Gate::denies('ticket_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $ticket->load('categoryid');

        return view('admin.tickets.show', compact('ticket'));
    }

    public function destroy(Ticket $ticket)
    {
        abort_if(Gate::denies('ticket_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $ticket->delete();

        return back();
    }

    public function massDestroy(MassDestroyTicketRequest $request)
    {
        Ticket::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

app/Http/Controllers/Student/TicketsController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyTicketRequest;
use App\Http\Requests\StoreTicketRequest;
use App\Http\Requests\UpdateTicketRequest;
use App\Ticket;
use App\Ticketcategory;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Storage;

class TicketsController extends Controller
{
    public function index()
    {
        
        $tickets = Ticket::where('userid',auth()->user()->id)
        ->orderBy('id','DESC')
        ->get();

        return view('students.tickets.index', compact('tickets'));
    }

    public function create()
    {
        
        $categoryids = Ticketcategory::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('students.tickets.create', compact('categoryids'));
    }

    public function store(Request $request)
    {
        $ticket=new Ticket;
        $ticket->userid=$request->userid;
        $ticket->query=$request->query1;
        $ticket->status=$request->status;
        $ticket->categoryid_id=$request->categoryid_id;

        if($request->hasFile('photo'))
        {
            $photo=$request->file('photo')->store('tickets','s3');
            Storage::disk('s3')->setVisibility($photo,'public');
            $url=Storage::disk('s3')->url($photo);
            $ticket->photo=$url;


        }

        
        $ticket->save();

        //$user_id=auth()->user()->id;
        //$photo=$request->file('photo')->store('tickets','s3');
        
        
        //$ticket = Ticket::create($request->all());
        //$ticket1=Ticket::where('userid',$user_id)->first();
        //Ticket::latest->where('userid',$user_id)->first()->update([
            //'photo' => Storage::disk('s3')->url($photo)
        //]);

        return redirect()->route('support');
    }

    
    
    public function show($id)
    {
        $ticket=Ticket::find($id);
        $ticket->load('categoryid');

        return view('students.tickets.show', compact('ticket'));
    }

    
    
}

resources/views/admin/tickets/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.ticket.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.tickets.store") }}" enctype="multipart/form-data">
            @csrf

            <input type="hidden" name="userid" value="{{auth()->user()->id}}">
            <input type="hidden" name="status" value="Open">
            <div class="form-group">
                <label class="required" for="categoryid_id">{{ trans('cruds.ticket.fields.categoryid') }}</label>
                <select class="form-control select2 {{ $errors->has('categoryid') ? 'is-invalid' : '' }}" name="categoryid_id" id="categoryid_id" required>
                    @foreach($categoryids as $id => $categoryid)
                        <option value="{{ $id }}" {{ old('categoryid_id') == $id ? 'selected' : '' }}>{{ $categoryid }}</option>
                    @endforeach
                </select>
                @if($errors->has('categoryid'))
                    <div class="invalid-feedback">
                        {{ $errors->first('categoryid') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.ticket.fields.categoryid_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="query">{{ trans('cruds.ticket.fields.query') }}</label>
                <textarea class="form-control {{ $errors->has('query') ? 'is-invalid' : '' }}" name="query" id="query" required>{{ old('query') }}</textarea>
                @if($errors->has('query'))
                    <div class="invalid-feedback">
                        {{ $errors->first('query') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.ticket.fields.query_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/tickets/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.ticket.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.tickets.update", [$ticket->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="categoryid_id">{{ trans('cruds.ticket.fields.categoryid') }}</label>
                <select class="form-control select2 {{ $errors->has('categoryid') ? 'is-invalid' : '' }}" name="categoryid_id" id="categoryid_id" required>
                    @foreach($categoryids as $id => $categoryid)
                        <option value="{{ $id }}" {{ ($ticket->categoryid ? $ticket->categoryid->id : old('categoryid_id')) == $id ? 'selected' : '' }}>{{ $categoryid }}</option>
                    @endforeach
                </select>
                @if($errors->has('categoryid'))
                    <div class="invalid-feedback">
                        {{ $errors->first('categoryid') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.ticket.fields.categoryid_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="query">{{ trans('cruds.ticket.fields.query') }}</label>
                <textarea class="form-control {{ $errors->has('query') ? 'is-invalid' : '' }}" name="query" id="query" required>{{ old('query', $ticket->query) }}</textarea>
                @if($errors->has('query'))
                    <div class="invalid-feedback">
                        {{ $errors->first('query') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.ticket.fields.query_helper') }}</span>
            </div>
            <div class="form-group">
                <label>{{ trans('cruds.ticket.fields.status') }}</label>
                <select class="form-control {{ $errors->has('status') ? 'is-invalid' : '' }}" name="status" id="status">
                    <option value disabled {{ old('status', null) === null ? 'selected' : '' }}>{{ trans('global.pleaseSelect') }}</option>
                    @foreach(App\Ticket::STATUS_SELECT as $key => $label)
                        <option value="{{ $key }}" {{ old('status', $ticket->status) === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
                    @endforeach
                </select>
                @if($errors->has('status'))
                    <div class="invalid-feedback">
                        {{ $errors->first('status') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.ticket.fields.status_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="response">{{ trans('cruds.ticket.fields.response') }}</label>
                <textarea class="form-control {{ $errors->has('response') ? 'is-invalid' : '' }}" name="response" id="response">{{ old('response', $ticket->response) }}</textarea>
                @if($errors->has('response'))
                    <div class="invalid-feedback">
                        {{ $errors->first('response') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.ticket.fields.response_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/tickets/index.blade.php
@extends('layouts.admin')
@section('content')
@can('ticket_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.tickets.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.ticket.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.ticket.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Ticket">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.ticket.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.ticket.fields.userid') }}
                        </th>
                        <th>
                            {{ trans('cruds.ticket.fields.categoryid') }}
                        </th>
                        <th>
                            {{ trans('cruds.ticket.fields.query') }}
                        </th>
                        <th>
                            {{ trans('cruds.ticket.fields.status') }}
                        </th>
                        <th>
                            {{ trans('cruds.ticket.fields.response') }}
                        </th>
                        <th>
                           Action &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($tickets as $key => $ticket)
                        <tr data-entry-id="{{ $ticket->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $ticket->id ?? '' }}
                            </td>
                            <td>
                                {{ $ticket->userid ?? '' }}
                            </td>
                            <td>
                                {{ $ticket->categoryid->name ?? '' }}
                            </td>
                            <td>
                                {{ $ticket->query ?? '' }}
                            </td>
                            <td>
                                {{ App\Ticket::STATUS_SELECT[$ticket->status] ?? '' }}
                            </td>
                            <td>
                                {{ $ticket->response ?? '' }}
                            </td>
                            <td>
                                @can('ticket_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.tickets.show', $ticket->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('ticket_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.tickets.edit', $ticket->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('ticket_delete')
                                    <form action="{{ route('admin.tickets.destroy', $ticket->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('ticket_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.tickets.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Ticket:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/tickets/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.ticket.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.tickets.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.ticket.fields.id') }}
                        </th>
                        <td>
                            {{ $ticket->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.ticket.fields.userid') }}
                        </th>
                        <td>
                            {{ $ticket->userid }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.ticket.fields.categoryid') }}
                        </th>
                        <td>
                            {{ $ticket->categoryid->name ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.ticket.fields.query') }}
                        </th>
                        <td>
                            {{ $ticket->query }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.ticket.fields.status') }}
                        </th>
                        <td>
                            {{ App\Ticket::STATUS_SELECT[$ticket->status] ?? '' }}
                        </td>
                    </tr>
                    @if(!empty($ticket->photo))
                    <tr>
                        <th>
                            Attachemnts
                        </th>
                        <td>
                            <img src="{{asset($ticket->photo)}}" style="width: 50px; height: 50px;">
                            <a href="{{$ticket->photo}}" target="_blank">View File </a>
                            
                        </td>
                    </tr>
                    @endif
                    <tr>
                        <th>
                            {{ trans('cruds.ticket.fields.response') }}
                        </th>
                        <td>
                            {{ $ticket->response }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.tickets.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection