routes/web.php
Route::POST('/updatestudentdetails/{id}','Admin\ProfilesController@updatedetails')->name('updatestudentdetails');
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Castes
    Route::delete('castes/destroy', 'CasteController@massDestroy')->name('castes.massDestroy');
    Route::resource('castes', 'CasteController');

    // Coursetypes
    Route::delete('coursetypes/destroy', 'CoursetypeController@massDestroy')->name('coursetypes.massDestroy');
    Route::resource('coursetypes', 'CoursetypeController');

    // Courses
    Route::delete('courses/destroy', 'CoursesController@massDestroy')->name('courses.massDestroy');
    Route::resource('courses', 'CoursesController');

    // Categories
    Route::delete('categories/destroy', 'CategoryController@massDestroy')->name('categories.massDestroy');
    Route::resource('categories', 'CategoryController');

    // Scholarship Providers

   
    Route::delete('scholarship-providers/destroy', 'ScholarshipProvidersController@massDestroy')->name('scholarship-providers.massDestroy');
    Route::resource('scholarship-providers', 'ScholarshipProvidersController');

    // Scholarships

    Route::delete('scholarships/destroy', 'ScholarshipsController@massDestroy')->name('scholarships.massDestroy');
    Route::post('scholarships/media', 'ScholarshipsController@storeMedia')->name('scholarships.storeMedia');
    Route::post('scholarships/ckmedia', 'ScholarshipsController@storeCKEditorImages')->name('scholarships.storeCKEditorImages');
    Route::resource('scholarships', 'ScholarshipsController');

   

    // Profiles
    Route::delete('profiles/destroy', 'ProfilesController@massDestroy')->name('profiles.massDestroy');
    Route::resource('profiles', 'ProfilesController');



    // Scholarship Achievers
    Route::delete('scholarship-achievers/destroy', 'ScholarshipAchieversController@massDestroy')->name('scholarship-achievers.massDestroy');
    Route::post('scholarship-achievers/media', 'ScholarshipAchieversController@storeMedia')->name('scholarship-achievers.storeMedia');
    Route::post('scholarship-achievers/ckmedia', 'ScholarshipAchieversController@storeCKEditorImages')->name('scholarship-achievers.storeCKEditorImages');
    Route::resource('scholarship-achievers', 'ScholarshipAchieversController');

     // Ticketcategories
    Route::delete('ticketcategories/destroy', 'TicketcategoriesController@massDestroy')->name('ticketcategories.massDestroy');
    Route::resource('ticketcategories', 'TicketcategoriesController');

    // Tickets
    Route::delete('tickets/destroy', 'TicketsController@massDestroy')->name('tickets.massDestroy');
    Route::resource('tickets', 'TicketsController');

    // Faq Categories
    Route::delete('faq-categories/destroy', 'FaqCategoryController@massDestroy')->name('faq-categories.massDestroy');
    Route::resource('faq-categories', 'FaqCategoryController');

    // Faq Questions
    Route::delete('faq-questions/destroy', 'FaqQuestionController@massDestroy')->name('faq-questions.massDestroy');
    Route::resource('faq-questions', 'FaqQuestionController');
    
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});



Route::get('/students','Student\HomeController@index')->name('students.home');

Route::get('/preview','Student\ProfileController@preview')->name('preview');
//Student Profile Controller
Route::group(['prefix' => 'student','namespace' => 'Student'], function(){

Route::get('/createprofile','ProfileController@create')->name('createprofile');

Route::POST('/details','ProfileController@updatedetails')->name('details');
Route::POST('/servicepreview','ProfileController@servicedetails')->name('servicepreview');

Route::POST('/createprofile','ProfileController@store')->name('storeprofile');
Route::get('/editprofile/{id}','ProfileController@edit')->name('editprofile');
Route::POST('updateprofile/{id}','ProfileController@update')->name('updateprofile');



Route::get('course/get_coursetype','ProfileController@getcourse')->name('getcourse');

Route::get('documents','ProfileController@documents')->name('documents');
Route::POST('aadharupload','ProfileController@aadharupload')->name('aadharupload');

Route::POST('panupload','ProfileController@panupload')->name('panupload');
Route::POST('casteupload','ProfileController@casteupload')->name('casteupload');
Route::POST('phupload','ProfileController@phupload')->name('phupload');
Route::POST('deathupload','ProfileController@deathupload')->name('deathupload');
Route::POST('photoupload','ProfileController@photoupload')->name('photoupload');
Route::POST('addproofupload','ProfileController@addproofupload')->name('addproofupload');
Route::POST('domupload','ProfileController@domupload')->name('domupload');
Route::POST('icupload','ProfileController@icupload')->name('icupload');
Route::POST('passbookupload','ProfileController@passbookupload')->name('passbookupload');
Route::POST('clgidupload','ProfileController@clgidupload')->name('clgidupload');
Route::POST('bonafideupload','ProfileController@bonafideupload')->name('bonafideupload');
Route::POST('admissionupload','ProfileController@admissionupload')->name('admissionupload');
Route::POST('cfupload','ProfileController@cfupload')->name('cfupload');
Route::POST('hfupload','ProfileController@hfupload')->name('hfupload');
Route::POST('class10upload','ProfileController@class10upload')->name('class10upload');
Route::POST('class12upload','ProfileController@class12upload')->name('class12upload');
Route::POST('diplomaupload','ProfileController@diplomaupload')->name('diplomaupload');
Route::POST('gradupload','ProfileController@gradupload')->name('gradupload');
Route::POST('prevupload','ProfileController@prevupload')->name('prevupload');



//sfc

Route::get('preview','ProfileController@sfc')->name('sfc');



 //Student Search & Apply Scholarship

Route::get('/myscholarship','HomeController@myscholarship')->name('myscholarship');

Route::get('/details/{id}','HomeController@showdetails')->name('showdetails');

//Support Controller
Route::get('/support','TicketsController@index')->name('support');

Route::get('/createquery','TicketsController@create')->name('createquery');
Route::POST('storequery','TicketsController@store')->name('storequery');

Route::get('viewresponse/{id}','TicketsController@show')->name('response');
});

 Route::get('showapplications/{id}','SetupscholarshipController@showapplications')->name('showapplications');

Route::get('filteredview/{id}','ScholarshipProvider\SetupscholarshipController@filteredview')->name('filteredview');
Route::get('/scholarshipproviders','ScholarshipProvider\HomeController@index')->name('providers.home');
Route::get('/sfcngostudentlist','SFCNGO\HomeController@sfc_student_list')->name('sfc_student_list');

Route::get('/sfcngo','SFCNGO\HomeController@index')->name('sfc.home');

Route::GET('/sfcngo/applications','SFCNGO\HomeController@sfcapplications')->name('sfcapplications');
Route::POST('sfcsearchstatus','SFCNGO\HomeController@searchstatus')->name('sfcsearchstatus');
Route::GET('profileshow/{id}','SFCNGO\HomeController@profileshow')->name('profileshow');

Route::group(['prefix'=>'provider','namespace'=>'ScholarshipProvider'],function(){

     Route::delete('setupscholarships/destroy', 'SetupscholarshipController@massDestroy')->name('massDestroy');
    Route::post('setupscholarships/media', 'SetupscholarshipController@storeMedia')->name('setupscholarships.storeMedia');
    Route::post('setupscholarships/ckmedia', 'SetupscholarshipController@storeCKEditorImages')->name('setupscholarships.storeCKEditorImages');
    Route::resource('setupscholarships', 'SetupscholarshipController');

    Route::get('promotion','SetupscholarshipController@promotion')->name('promotion');
    Route::get('setup','SetupscholarshipController@index')->name('setup');
    Route::get('listscheme','SetupscholarshipController@listscheme')->name('listscheme');
     Route::get('createschol','SetupscholarshipController@create')->name('createscholarship');
       Route::POST('createschol','SetupscholarshipController@store')->name('storescholarship');

    Route::get('show/{id}','SetupscholarshipController@show')->name('showscholarship');
    Route::get('edit/{id}','SetupscholarshipController@edit')->name('editscholarship');
    Route::POST('edit/{id}','SetupscholarshipController@update')->name('updatescholarship');
    Route::DELETE('delete/{id}','SetupscholarshipController@destroy')->name('deletescholarship');

    Route::get('showp/{id}','SetupscholarshipController@showprofile')->name('showprofile');
    Route::get('showapplications/{id}','SetupscholarshipController@showapplications')->name('showapplications');



});
Route::POST('applications/{id}','Student\HomeController@apply')->name('apply');
Route::get('/shortlisted/{id}','ScholarshipProvider\HomeController@Shortlised')->name('Shortlised');
Route::get('/rejected/{id}','ScholarshipProvider\HomeController@Rejected')->name('Rejected');

app/FaqCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class FaqCategory extends Model
{
    //
     use SoftDeletes;

    public $table = 'faq_categories';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'category',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/FaqCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\FaqCategory;
use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyFaqCategoryRequest;
use App\Http\Requests\StoreFaqCategoryRequest;
use App\Http\Requests\UpdateFaqCategoryRequest;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class FaqCategoryController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('faq_category_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $faqCategories = FaqCategory::all();

        return view('admin.faqCategories.index', compact('faqCategories'));
    }

    public function create()
    {
        abort_if(Gate::denies('faq_category_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.faqCategories.create');
    }

    public function store(StoreFaqCategoryRequest $request)
    {
        $faqCategory = FaqCategory::create($request->all());

        return redirect()->route('admin.faq-categories.index');
    }

    public function edit(FaqCategory $faqCategory)
    {
        abort_if(Gate::denies('faq_category_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.faqCategories.edit', compact('faqCategory'));
    }

    public function update(UpdateFaqCategoryRequest $request, FaqCategory $faqCategory)
    {
        $faqCategory->update($request->all());

        return redirect()->route('admin.faq-categories.index');
    }

    public function show(FaqCategory $faqCategory)
    {
        abort_if(Gate::denies('faq_category_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.faqCategories.show', compact('faqCategory'));
    }

    public function destroy(FaqCategory $faqCategory)
    {
        abort_if(Gate::denies('faq_category_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $faqCategory->delete();

        return back();
    }

    public function massDestroy(MassDestroyFaqCategoryRequest $request)
    {
        FaqCategory::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/faqCategories/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.faqCategory.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.faq-categories.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="category">{{ trans('cruds.faqCategory.fields.category') }}</label>
                <input class="form-control {{ $errors->has('category') ? 'is-invalid' : '' }}" type="text" name="category" id="category" value="{{ old('category', '') }}" required>
                @if($errors->has('category'))
                    <div class="invalid-feedback">
                        {{ $errors->first('category') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.faqCategory.fields.category_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/faqCategories/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.faqCategory.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.faq-categories.update", [$faqCategory->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="category">{{ trans('cruds.faqCategory.fields.category') }}</label>
                <input class="form-control {{ $errors->has('category') ? 'is-invalid' : '' }}" type="text" name="category" id="category" value="{{ old('category', $faqCategory->category) }}" required>
                @if($errors->has('category'))
                    <div class="invalid-feedback">
                        {{ $errors->first('category') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.faqCategory.fields.category_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/faqCategories/index.blade.php
@extends('layouts.admin')
@section('content')
@can('faq_category_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.faq-categories.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.faqCategory.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.faqCategory.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-FaqCategory">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.faqCategory.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.faqCategory.fields.category') }}
                        </th>
                        <th>
                            Action&nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($faqCategories as $key => $faqCategory)
                        <tr data-entry-id="{{ $faqCategory->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $faqCategory->id ?? '' }}
                            </td>
                            <td>
                                {{ $faqCategory->category ?? '' }}
                            </td>
                            <td>
                                @can('faq_category_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.faq-categories.show', $faqCategory->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('faq_category_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.faq-categories.edit', $faqCategory->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('faq_category_delete')
                                    <form action="{{ route('admin.faq-categories.destroy', $faqCategory->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('faq_category_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.faq-categories.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-FaqCategory:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/faqCategories/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.faqCategory.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.faq-categories.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.faqCategory.fields.id') }}
                        </th>
                        <td>
                            {{ $faqCategory->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.faqCategory.fields.category') }}
                        </th>
                        <td>
                            {{ $faqCategory->category }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.faq-categories.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection